// Generated by CoffeeScript 1.6.3
var assert, chai, datetime;

if (typeof require !== "undefined" && require !== null) {
  chai = require('chai');
  datetime = require('../datetime');
}

assert = chai.assert;

describe('datetime', function() {
  describe('#isoformat()', function() {
    return it('should format date as ISO', function() {
      var d;
      d = new Date(2013, 8, 1, 16);
      d.setMinutes(d.getMinutes() - d.getTimezoneOffset());
      return assert.equal(datetime.isoformat(d), '2013-09-01T16:00:00.00');
    });
  });
  return describe('#isoparse()', function() {
    return it('should parse date in ISO format', function() {
      var d;
      d = datetime.isoparse('2013-09-01T16:00:00.00');
      d.setMinutes(d.getMinutes() - d.getTimezoneOffset());
      assert.equal(d.getFullYear(), 2013);
      assert.equal(d.getMonth(), 8);
      assert.equal(d.getHours(), 16);
      return assert.equal(d.getMinutes(), 0);
    });
  });
});
